### ISSUE TITLE
croak not imported into Test::DBIx::Class::SchemaManager::Trait::SQLite

### ISSUE THREAD

**Issue by simonamor** [jjn1056/Test-DBIx-Class#42] opened 2016-11-11 12:18 UTC
When specifying a dsn for SQLite that's not quite in the expected format (but still works), you get an error after performing tests.

(in cleanup) Undefined subroutine &Test::DBIx::Class::SchemaManager::Trait::SQLite::croak called at /home/simon/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/Test/DBIx/Class/SchemaManager/Trait/SQLite.pm line 22 during global destruction.

The DSN format 'DBI:SQLite:$dbfile' is valid according to quite a few places in the DBD::SQLite docs so I had

    connect_info => [ 'DBI:SQLite:/tmp/foo.sqlite',undef,undef],

Changing this to 'DBI:SQLite:dbname=/tmp/foo.sqlite' gets rid of the error but the lack of croak is hiding the actual error message. Adding the following at line 7 of Test/DBIx/Class/SchemaManager/Trait/SQLite.pm results in the error being shown correctly.

    use Carp;

(in cleanup) Couldn't find dbname in sqlite dsn 'DBI:SQLite:/tmp/foo.sqlite' at /home/simon/perl5/perlbrew/perls/perl-5.20.1/lib/site_perl/5.20.1/x86_64-linux/Class/MOP/Method/Wrapped.pm line 57.

[test-dbic.txt](https://github.com/jjn1056/Test-DBIx-Class/files/585753/test-dbic.txt)

To see the error, get the file above and use prove on it..
$ prove test-dbic.txt

**Comment by colinnewell** [comment] 2016-11-11 14:15
I use that format too, I've pushed a fix to github, and I'll see about doing a release soon.

**Comment by colinnewell** [comment] 2016-11-12 09:16
The more I think about this one I think the croak should be changed to a die.  The error message you see when it works refers to Class::MOP::Wrapped which obviously has nothing to do with the actual code.  This crash isn't caused by a direct call to the method, so it's not really the callers fault anyway, it's somewhere much closer to the start.

It would make more sense to die so that you can see the real source of the error, and then figure out why the dsn failed to be extracted correctly.

**Comment by colinnewell** [comment] 2016-11-14 19:56
New release is on it's way to CPAN.

**Closed by colinnewell** 2016-11-14 19:56 UTC
